CREATE TABLE IF NOT EXISTS user_invitations(
    id UUID PRIMARY KEY,
    tenant_id UUID NOT NULL REFERENCES tenants(id),
    invited_by UUID NOT NULL REFERENCES users(id),
    invited_email TEXT NOT NULL,
    role VARCHAR(20) NOT NULL CHECK (role IN ('MANAGER', 'OPERATOR', 'DRIVER', 'AUDITOR')),
    token UUID NOT NULL,
    status VARCHAR(20) DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'ACCEPTED', 'EXPIRED', 'REVOKED')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    accepted_at TIMESTAMP WITH TIME ZONE,
    expired_at TIMESTAMP WITH TIME ZONE,
    deleted_at TIMESTAMP WITH TIME ZONE
);